apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscustomerserviceprod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dmscustomerserviceprod
  template:
    metadata:
      labels:
        app: dmscustomerserviceprod
    spec:
      nodeSelector:
        "kubernetes.io/os": linux      
      containers:
        - name: dmscustomerserviceprod
          image: microservicesacrafrprd.azurecr.io/dmscustomerserviceprod
          ports:
          - containerPort: 80