apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscustomerserviceqa 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmscustomerserviceqa
  template:
    metadata:
      labels:
        app: dmscustomerserviceqa 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux      
      containers:
        - name: dmscustomerserviceqa
          image: microservicesacrafrqa.azurecr.io/dmscustomerserviceqa
          ports:
          - containerPort: 80