apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscustomerservice 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dmscustomerservice
  template:
    metadata:
      labels:
        app: dmscustomerservice 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux      
      containers:
        - name: dmscustomerservice 
          image: microservicesacrafrqa.azurecr.io/dmscustomerservice
          ports:
          - containerPort: 80