apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscustomerservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmscustomerservice
  template:
    metadata:
      labels:
        app: dmscustomerservice 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux      
      containers:
        - name: dmscustomerservice 
          image: microservicesacrafrdev.azurecr.io/dmscustomerservice:latest
          ports:
          - containerPort: 80